name: Deploy React-Chat-Widget Control Sample App

on:
  workflow_dispatch:
    inputs:
      orgId:
        description: 'Organization Id'
        required: false
        default: 'd367c413-e0b9-408b-ae1c-382499b369ae'
      orgUrl:
        description: 'Organization URL'
        require: false
        default: 'https://omnichannel-crm.omnichannelengagementhub.com'
      widgetId:
        description: 'Widget Id'
        require: false
        default: '3a352b95-5d67-4e47-af28-eca029b03928'
      email:
        description: 'Email'
        require: false
        default: 'foo@bar.com'

env:
  orgId: ${{ github.event.inputs.orgId }}
  orgUrl: ${{ github.event.inputs.orgUrl }}
  widgetId: ${{ github.event.inputs.widgetId }}
  email: ${{ github.event.inputs.email }}
  rootUrl: https://demo.edwardtran.me/omnichannel-chat-sdk/react-chat-widget-control
  CI: false

jobs:
  react-chat-widget-control:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.X

      - name: Download react-chat-widget-control
        run: |
          npx github-files-fetcher --url="https://github.com/microsoft/omnichannel-chat-sdk-samples/tree/main/react-chat-widget-control"

      - name: Install NPM Packages
        working-directory: react-chat-widget-control
        run: |
          yarn install

      - name: Update @microsoft/omnichannel-chat-sdk
        working-directory: react-chat-widget-control
        run: |
          yarn remove @microsoft/omnichannel-chat-sdk
          yarn add @microsoft/omnichannel-chat-sdk@latest

      - name: Configure Environment
        working-directory: react-chat-widget-control
        run: |
          echo "# Chat Widget Config" > .env
          echo "REACT_APP_orgId='$orgId'" >> .env
          echo "REACT_APP_orgUrl='$orgUrl'" >> .env
          echo "REACT_APP_widgetId='$widgetId'" >> .env
          echo "" >> .env
          echo "# Transcript Config" >> .env
          echo "REACT_APP_email='$email'" >> .env

      - name: Set App Server Root
        working-directory: react-chat-widget-control
        run: |
          echo "$(cat package.json | jq --arg url ${rootUrl} '. + {homepage: $url}')" > package.json

      - name: Build App
        working-directory: react-chat-widget-control
        run: |
          yarn build

      - name: Configure Deployment
        run: |
          mv react-chat-widget-control tmp
          cp -r tmp/build .
          mv build react-chat-widget-control

      - name: Clean Up
        run: |
          rm -rf tmp

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: react-chat-widget-control
          target-folder: omnichannel-chat-sdk/react-chat-widget-control
