name: Deploy BotFramework-WebChat Control Sample App

on:
  workflow_dispatch:
    inputs:
      orgId:
        description: 'Organization Id'
        required: false
        default: 'd367c413-e0b9-408b-ae1c-382499b369ae'
      orgUrl:
        description: 'Organization URL'
        require: false
        default: 'https://omnichannel-crm.omnichannelengagementhub.com'
      widgetId:
        description: 'Widget Id'
        require: false
        default: 'https://omnichannel-crm.omnichannelengagementhub.com'
      email:
        description: 'Email'
        require: false
        default: 'foo@bar.com'

env:
  orgId: ${{ github.event.inputs.orgId }}
  orgUrl: ${{ github.event.inputs.orgUrl }}
  widgetId: ${{ github.event.inputs.widgetId }}
  email: ${{ github.event.inputs.email }}
  rootUrl: https://blog.edwardtran.me/omnichannel-demos/omnichannel-chat-sdk/botframework-webchat-control
  CI: false

jobs:

  botframework-webchat-control:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 12.X

      - name: Download botframework-webchat-control
        run: |
          npx github-files-fetcher --url="https://github.com/microsoft/omnichannel-chat-sdk/tree/main/samples/botframework-webchat-control"

      - name: Install NPM Packages
        working-directory: botframework-webchat-control
        run: |
          npm ci

      - name: Update @microsoft/omnichannel-chat-sdk
        working-directory: botframework-webchat-control
        run: |
          npm uninstall @microsoft/omnichannel-chat-sdk
          npm install @microsoft/omnichannel-chat-sdk@latest --save-dev

      - name: Configure Environment
        working-directory: botframework-webchat-control
        run: |
          echo "# Chat Widget Config" > .env
          echo "REACT_APP_orgId='$orgId'" >> .env
          echo "REACT_APP_orgUrl='$orgUrl'" >> .env
          echo "REACT_APP_widgetId='$widgetId'" >> .env
          echo "" >> .env
          echo "# Transcript Config" >> .env
          echo "REACT_APP_email='$email'" >> .env

      - name: Set App Server Root
        working-directory: botframework-webchat-control
        run: |
          echo "$(cat package.json | jq --arg url ${rootUrl} '. + {homepage: $url}')" > package.json

      - name: Build App
        working-directory: botframework-webchat-control
        run: |
          npm run build

      - name: Configure Deployment
        run: |
          mv botframework-webchat-control tmp
          cp -r tmp/build .
          mv build botframework-webchat-control
          ls

      - name: Clean Up
        run: |
          rm -rf tmp

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: botframework-webchat-control
          target-folder: omnichannel-chat-sdk/botframework-webchat-control